# ###############
#  db,wordpress
version: "3"
services:
   db:
     image: mysql:5.7
     container_name: wordpress-mysql
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
#
   wordpress:
     container_name: wordpress
     depends_on:
       - db
     image: wordpress:latest
     volumes:
        - ./wp_site:/var/www/html
     ports:
       - "83:80"
       # - "443:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     logging:
       driver: json-file
       options:
         max-size: "200k"
         max-file: "10"