cluster.name: elasticsearch-cluster
node.name: es-node1
network.bind_host: 0.0.0.0
# network.publish_host: `your ip`
network.publish_host: 192.168.1.24
http.port: 9201
transport.tcp.port: 9301
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
discovery.zen.ping.unicast.hosts: ["192.168.1.24:9301","192.168.1.24:9302","192.168.1.24:9303"]
discovery.zen.minimum_master_nodes: 2
