version: '3'
services:
  redis-master:
    image: redis:4.0.9
    container_name: redis-master
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis-master/conf/redis-master.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis-master/data:/data
    # ports:
    #   - "36379:6379"
  redis-slave:
    image: redis:4.0.9
    # container_name: redis-slave
    command: redis-server --slaveof redis-master 6379
    restart: always
    environment:
      TZ: Asia/Shanghai
    links:
      - redis-master
    # ports:
    #   - "46379:6379"
  redis-sentinel:
    build: sentinel
    # container_name: redis-sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - redis-master
      - redis-slave
    # ports:
    #  - "26379:26379"