version: '3'
services:
  rsyslog:
    image: voxxit/rsyslog
    container_name: rsyslog
    ports:
      - "514:514"
      - "514:514/udp"
    volumes:
      - ./rsyslog.d:/etc/rsyslog.d
      - ./log:/var/log
    restart: always
  nginx:
    image: nginx:alpine # 下面截图里用了我的rtmp镜像，效果相同
    container_name: rsyslog-nginx
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://192.168.1.24:514" # 内网IP
        tag: "{{.Name}}.{{.ID}}"
    ports:
      - "8009:80"
    restart: always
    depends_on:
      - rsyslog