version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dblog/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'dblog'
      MYSQL_USER: 'dblog'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'

